export const level: string[] = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X  F                                             X",
    "X XXXXXXXXXXXXXXX                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X             XXXXXXXXXXXXXXXXXXXXXXX            X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                      XXXXXXXXXXX",
    "X                                                X",
    "X        P                                       X",
    "X                                                X",
    "X                  XXXXXXX    XXXXXXX            X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "X                                                X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",

]